example:
  key: "example-value" # 테스트용 예제 값

spring:
  datasource:
    url: jdbc:h2:mem:testdb # H2 메모리 데이터베이스 설정
    username: sa
    password:
    driver-class-name: org.h2.Driver

my:
  custom:
    property: "This is a custom property"

