example:
  key: "example-value"
spring:
  application:
    name: config-client
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
server:
  port: 8888
